/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.karaf.vineyard.registry.storage;

/**
 * SQL Queries Constants.
 */
public final class SqlRegistryConstants {

    //TODO public final static String createTableQueryGenericTemplate = "";
    //TODO public final static String createTableQueryMySQLTemplate = "";

    public final static String DATABASE_SCHEMA = "VINEYARD";

    protected final static String[] createTableQueryDerbyTemplate = new String[] {
            "CREATE SCHEMA " + DATABASE_SCHEMA,

            "CREATE TABLE " + DATABASE_SCHEMA + ".DATAFORMAT(" +
                    " id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT DATAFORMAT_PK PRIMARY KEY," +
                    " name VARCHAR(200) NOT NULL," +
                    " sample VARCHAR(8192)," +
                    " dataschema VARCHAR(8192))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".API(" +
                    " id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT API_PK PRIMARY KEY," +
                    " name VARCHAR(200) NOT NULL," +
                    " context VARCHAR(200)," +
                    " description VARCHAR(8192)," +
                    " version VARCHAR(200))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".METADATA(" +
                    " id_api SMALLINT," +
                    " metakey VARCHAR(200)," +
                    " metavalue VARCHAR(500)," +
                    " CONSTRAINT API_METADATA_API_FK FOREIGN KEY (id_api) REFERENCES " + DATABASE_SCHEMA + ".API (id))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".RESOURCES(" +
                    " id_api SMALLINT," +
                    " path VARCHAR(200)," +
                    " method VARCHAR(200)," +
                    " bridge VARCHAR(200)," +
                    " id_dataformat_in SMALLINT," +
                    " id_dataformat_out SMALLINT," +
                    " use_bridge BOOLEAN, " +
                    " response CLOG, " +
                    " CONSTRAINT RESOURCES_DF_IN_FK FOREIGN KEY (id_dataformat_in) REFERENCES " + DATABASE_SCHEMA + ".DATAFORMAT (id), " +
                    " CONSTRAINT RESOURCES_DF_OUT_FK FOREIGN KEY (id_dataformat_out) REFERENCES " + DATABASE_SCHEMA + ".DATAFORMAT (id), " +
                    " CONSTRAINT RESOURCES_API_FK FOREIGN KEY (id_api) REFERENCES " + DATABASE_SCHEMA + ".API (id))"
    };

    /** Select queries */
    public final static String selectDataformatSql =
            "select id, name, sample, dataschema " +
                    "from " + DATABASE_SCHEMA + ".DATAFORMAT ";

    public final static String selectApiSql =
            "select id, name, context, description, version " +
                    "from " + DATABASE_SCHEMA + ".API ";

    public final static String selectApiMetadataSql =
            "select metakey, metavalue " +
                    "from " + DATABASE_SCHEMA + ".METADATA " +
                    "where id_api = ? ";

    public final static String selectApiResourcesSql =
            "select path, method, bridge, use_bridge, response " +
                    "from " + DATABASE_SCHEMA + ".RESOURCES " +
                    "where id_api = ? ";

    /** Insert queries */
    public final static String insertDataformatSql =
            "insert into " + DATABASE_SCHEMA + ".DATAFORMAT " +
                    "(name, sample, dataschema) " +
                    "values (?, ?, ?)";

    public final static String insertApiSql =
            "insert into " + DATABASE_SCHEMA + ".API " +
                    "(name, context, description, version) " +
                    "values (?, ?, ?, ?)";

    public final static String insertApiMetadataSql =
            "insert into " + DATABASE_SCHEMA + ".METADATA " +
                    "(id_api, metakey, metavalue) " +
                    "values (?, ?, ?)";

    public final static String insertApiResourcesSql =
            "insert into " + DATABASE_SCHEMA + ".RESOURCES " +
                    "(id_api, path, method, bridge use_bridge, response) " +
                    "values (?, ?, ?, ?, ?, ?)";

    /** Update queries */
    public final static String updateDataformatSql =
            "update " + DATABASE_SCHEMA + ".DATAFORMAT " +
                    "set name = ?, sample = ?, dataschema = ? " +
                    "where id = ?";

    public final static String updateApiSql =
            "update " + DATABASE_SCHEMA + ".API " +
                    "set name = ?, context = ?, description = ?, version = ? " +
                    "where id = ?";

    public final static String updateApiMetadataSql =
            "update " + DATABASE_SCHEMA + ".METADATA " +
                    "set metakey = ?, metavalue = ? " +
                    "where id_api = ?";

    public final static String updateApiResourcesSql =
            "update " + DATABASE_SCHEMA + ".RESOURCES " +
                    "set path = ?, method = ?, bridge = ? , use_bridge = ?, response = ? " +
                    "where id_api = ?";

    /** Delete queries */
    public final static String deleteDataformatSql =
            "delete from " + DATABASE_SCHEMA + ".DATAFORMAT where id = ?";

    public final static String deleteApiSql =
            "delete from " + DATABASE_SCHEMA + ".API where id = ?";

    public final static String deleteApiMetadataSql =
            "delete from " + DATABASE_SCHEMA + ".METADATA where id_api = ?";

    public final static String deleteApiResourcesSql =
            "delete from " + DATABASE_SCHEMA + ".RESOURCES where id_api = ?";
}
