/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.karaf.vineyard.registry.storage;

/**
 * SQL Queries Constants.
 */
public final class SqlRegistryConstants {

    //TODO public final static String createTableQueryGenericTemplate = "";
    //TODO public final static String createTableQueryMySQLTemplate = "";

    public final static String DATABASE_SCHEMA = "VINEYARD";

    public final static String[] createTableQueryDerbyTemplate = new String[] {
            "CREATE SCHEMA " + DATABASE_SCHEMA,

            "CREATE TABLE " + DATABASE_SCHEMA + ".DATAFORMAT(id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY "
                    + " CONSTRAINT DATAFORMAT_PK PRIMARY KEY, name VARCHAR(200) NOT NULL, sample VARCHAR(8192),"
                    + " dataschema VARCHAR(8192))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".RESTAPI(id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY "
                    + " CONSTRAINT RESTAPI_PK PRIMARY KEY, name VARCHAR(200) NOT NULL, description VARCHAR(8192),"
                    + " endpoint VARCHAR(500), id_dataformat SMALLINT, context VARCHAR(200)"
                    + " CONSTRAINT RESTAPI_DATAFORMAT_FK FOREIGN KEY (id_dataformat) REFERENCES " + DATABASE_SCHEMA + ".DATAFORMAT (id))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".RESTAPI_METADATA(id_restapi SMALLINT, metakey VARCHAR(200), metavalue VARCHAR(500), "
                    + " CONSTRAINT RESTAPI_METADATA_RESTAPI_FK FOREIGN KEY (id_restapi) REFERENCES " + DATABASE_SCHEMA + ".RESTAPI (id))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".RESTAPI_RESOURCES(id_restapi SMALLINT, path VARCHAR(200), method VARCHAR(200), "
                    + " CONSTRAINT RESTAPI_RESOURCES_RESTAPI_FK FOREIGN KEY (id_restapi) REFERENCES " + DATABASE_SCHEMA + ".RESTAPI (id))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".JMSAPI(id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY"
                    + " CONSTRAINT JMSAPI_PK PRIMARY KEY, name VARCHAR(200) NOT NULL, description VARCHAR(8192),"
                    + " endpoint VARCHAR(500), id_dataformat SMALLINT, connectionFactory VARCHAR(200),"
                    + " destination VARCHAR(200), type VARCHAR(200),"
                    + " CONSTRAINT JMSAPI_DATAFORMAT_FK FOREIGN KEY (id_dataformat) REFERENCES " + DATABASE_SCHEMA + ".DATAFORMAT (id))",

            "CREATE TABLE " + DATABASE_SCHEMA + ".JMSAPI_METADATA(id_jmsapi SMALLINT, metakey VARCHAR(200), metavalue VARCHAR(500), "
                    + " CONSTRAINT JMSAPI_METADATA_JMSAPI_FK FOREIGN KEY (id_jmsapi) REFERENCES " + DATABASE_SCHEMA + ".JMSAPI (id))"
    };

    /** Select queries */
    public final static String selectDataformatSql =
            "select id, name, sample, dataschema "
            + "from " + DATABASE_SCHEMA + ".DATAFORMAT";

    public final static String selectRestApiSql =
            "select id, name, description, endpoint, context, id_dataformat "
            + "from " + DATABASE_SCHEMA + ".RESTAPI";

    public final static String selectRestApiMetadataSql =
            "select metakey, metavalue "
            + "from " + DATABASE_SCHEMA + ".RESTAPI_METADATA "
            + "where id_restapi = ? ";

    public final static String selectRestApiResourcesSql =
            "select path, method "
            + "from " + DATABASE_SCHEMA + ".RESTAPI_RESOURCES "
            + "where id_restapi = ? ";

    public final static String selectJmsApiSql =
            "select id, name, description, endpoint, connectionFactory, destination, type, id_dataformat "
                    + "from " + DATABASE_SCHEMA + ".JMSAPI";

    public final static String selectJmsApiMetadataSql =
            "select metakey, metavalue "
                    + "from " + DATABASE_SCHEMA + ".JMSAPI_METADATA "
                    + "where id_jmsapi = ? ";

    /** Insert queries */
    public final static String insertDataformatSql =
            "insert into " + DATABASE_SCHEMA + ".DATAFORMAT "
                    + "(name, sample, dataschema) "
                    + "values (?, ?, ?)";

    public final static String insertRestApiSql =
            "insert into " + DATABASE_SCHEMA + ".RESTAPI "
                    + "(name, description, endpoint, context, id_dataformat) "
                    + "values (?, ?, ?, ?, ?)";

    public final static String insertRestApiMetadataSql =
            "insert into " + DATABASE_SCHEMA + ".RESTAPI_METADATA "
                    + "(id_restapi, metakey, metavalue) "
                    + "values (?, ?, ?)";

    public final static String insertRestApiResourcesSql =
            "insert into " + DATABASE_SCHEMA + ".RESTAPI_RESOURCES "
                    + "(id_restapi, path, method) "
                    + "values (?, ?, ?)";

    public final static String insertJmsApiSql =
            "insert into " + DATABASE_SCHEMA + ".JMSAPI "
                    + "(name, description, endpoint, connectionFactory, destination, type, id_dataformat) "
                    + "values (?, ?, ?, ?, ?, ?, ?)";

    public final static String insertJmsApiMetadataSql =
            "insert into " + DATABASE_SCHEMA + ".JMSAPI_METADATA "
                    + "(id_jmsapi, metakey, metavalue) "
                    + "values (?, ?, ?)";

    /** Update queries */
    public final static String updateDataformatSql =
            "update " + DATABASE_SCHEMA + ".DATAFORMAT "
                    + "set name = ?, sample = ?, dataschema = ? "
                    + "where id = ?";

    public final static String updateRestApiSql =
            "update " + DATABASE_SCHEMA + ".RESTAPI "
                    + "set name = ?, description = ?, endpoint = ?, context = ?, id_dataformat = ? "
                    + "where id = ?";

    public final static String updateRestApiMetadataSql =
            "update " + DATABASE_SCHEMA + ".RESTAPI_METADATA "
                    + "set metakey = ?, metavalue = ? "
                    + "where id_restapi = ?";

    public final static String updateRestApiResourcesSql =
            "update " + DATABASE_SCHEMA + ".RESTAPI_RESOURCES "
                    + "set path = ?, method = ? "
                    + "where id_restapi = ?";

    public final static String updateJmsApiSql =
            "update " + DATABASE_SCHEMA + ".JMSAPI "
                    + "set name = ?, description = ?, endpoint = ?, connectionFactory = ?, "
                    + "destination = ?, type = ?, id_dataformat = ? "
                    + "where id = ?";

    public final static String updateJmsApiMetadataSql =
            "update " + DATABASE_SCHEMA + ".JMSAPI_METADATA "
                    + "set metakey = ?, metavalue = ? "
                    + "where id_jmsapi = ?";


    /** Delete queries */
    public final static String deleteDataformatSql =
            "delete from " + DATABASE_SCHEMA + ".DATAFORMAT "
                    + "where id = ?";

    public final static String deleteRestApiSql =
            "delete from " + DATABASE_SCHEMA + ".RESTAPI "
                    + "where id = ?";

    public final static String deleteRestApiMetadataSql =
            "delete from " + DATABASE_SCHEMA + ".RESTAPI_METADATA "
                    + "where id_restapi = ?";

    public final static String deleteRestApiResourcesSql =
            "delete from " + DATABASE_SCHEMA + ".RESTAPI_RESOURCES "
                    + "where id_restapi = ?";

    public final static String deleteJmsApiSql =
            "delete from " + DATABASE_SCHEMA + ".JMSAPI "
                    + "where id = ?";

    public final static String deleteJmsApiMetadataSql =
            "delete from " + DATABASE_SCHEMA + ".JMSAPI_METADATA "
                    + "where id_jmsapi = ?";
}
